var character;
var age;
var isLoggedIn;
// age = 'luigi';
age = 30;
// isLoggedIn =  25;
isLoggedIn = true;
var ninjas = [];
// ninjas = [20, 12];
ninjas = ['Yoshi', 'Mario'];
var mixed = [];
mixed.push('hello');
mixed.push(20);
mixed.push(false);
console.log(mixed);
var uid;
uid = '123';
uid = 123;
var ninjaOne;
ninjaOne = { name: 'yodhi', age: 30 };
// ninjaOne = 'Kell'
var ninjatTwo;
ninjatTwo = { name: 'mario', age: 20, beltColour: 'black' };
